services:
  gitlab-runner:
    image: gitlab/gitlab-runner
    network_mode: host
    restart: always
    volumes:
      - ./srv:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    