services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - homelab
    ports:
      - "80:80"
    volumes:
      - artifacts:/usr/share/nginx/html
    restart: always

networks:
  homelab:
    name: homelab
    external: true

volumes:
  artifacts: