arp_args: ""
arp_strs: []
arp_strs_joined: ""
color: dark
hist_in_db: false
host: 0.0.0.0
ifaces: wlp2s0
influx_addr: ""
influx_bucket: ""
influx_enable: false
influx_org: ""
influx_skip_tls: false
influx_token: ""
log_level: info
nodepath: ""
pg_connect: ""
port: "8840"
prometheus_enable: false
shoutrrr_url: ""
theme: grayscale
timeout: 120
trim_hist: 48
use_db: sqlite
